helmBinary: helm3

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

templates:
  default: &default-redis-config
    namespace: default
    # Renovate used to upgrade this dependency.
    chart: bitnami/redis
    version: 20.4.0
releases:
  - name: redis
    <<: *default-redis-config
  - name: nginx
    namespace: default
    chart: ingress-nginx/ingress-nginx
    version: 4.11.3
